source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HMSegmentedControl_CodeEagle_Example', :exclusive => true do
  pod 'HMSegmentedControl_CodeEagle', :path => '../'
end

target 'HMSegmentedControl_CodeEagle_Tests', :exclusive => true do
  pod 'HMSegmentedControl_CodeEagle', :path => '../'

  
end
